stages:
  - setup
  - test
  - build

variables:
  # Set Python version to be used for testing
  PYTHON_VERSION: "3.9"

before_script:
  - apk add --no-cache python3 py3-pip # Install necessary packages for Alpine Linux
  - python3 -m venv py3
  - source py3/bin/activate
  - pip install --no-cache-dir -r requirements.txt

setup:
  stage: setup
  tags:
    - linux
  script:
    - echo "Setting up the environment..."

test:
  stage: test
  tags:
    - linux
  image: python:3.9
  before_script:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt
  script:
    - echo "Running unit tests..."
    - python -m unittest check_all_schedules_test.py
    # Generate test coverage report
    - pip install coverage
    - coverage run -m unittest check_all_schedules_test.py
    - coverage report
    - coverage xml -o coverage-report.xml
  artifacts:
    paths:
      - coverage-report.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage-report.xml

build:
  stage: build
  tags:
    - linux
  script:
    - echo "Docker login ..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.ellisbs.co.uk:7070 
    - echo "Building the Docker image..."
    - TIMESTAMP=$(date +'%Y.%m.%d.%H.%M')
    - docker build --push -t docker.ellisbs.co.uk:7070/check_all_schedules:$TIMESTAMP .
